### PR TITLE
Update P5 setup instructions

### PR DESCRIPTION
**Pull request by lmoureaux**
## Description

The setup instructions for P5 were broken by updates in the system. `gem-plotting-tools` is now installed system-wide and a setup script is provided centrally.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Setup instructions for P5 are broken. See eg the discussion after https://mattermost.web.cern.ch/cms-gem-ops/pl/4on3wpg5jpboff1cwjzjfmxd3e

## How Has This Been Tested?

* Checked that all tools are in `$PATH`
* Checked that `packageFiles4Docker.py` works

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

(Sorry about the branch name, it was created automatically by Github and I don't know how to change it)

### CODE REVIEW

**Comment by bdorney** [comment]
Was there an issue in setting up a `venv` at P5?  If so how was that resolved?  

Moreover instructions of this nature should not be removed.  But segmented into developer and user categories.  Return the previous `venv` instructions (if they work) and class them as a developer instructions.  

Add a statement that if someone doesn't know if they are a developer or user category that they fall into the user category.

**Comment by lmoureaux** [comment]
> Was there an issue in setting up a `venv` at P5? If so how was that resolved?

Yes. It is resolved by telling the user to use the system-wide install.

> Moreover instructions of this nature should not be removed. But segmented into developer and user categories. Return the previous `venv` instructions (if they work) and class them as a developer instructions.

They don't work anymore, and @jsturdy isn't interested in supporting non-system installs at P5 unless there's a good use-case (which I couldn't find in the Mattermost discussion linked to in the summary)

**Comment by bdorney** [comment]
> Yes. It is resolved by telling the user to use the system-wide install.

Yes that's fine for a user; but preserve the instructions for a developer.

> They don't work anymore, and @jsturdy isn't interested in supporting non-system installs at P5 unless there's a good use-case (which I couldn't find in the Mattermost discussion linked to in the summary)

Your mattermost link refers to a lack of `virtualenv` and `pip` but immediately below that link @mexanick and I both reference the `cc7` virtual machine which *does* have the packages required as illustrated [here](https://mattermost.web.cern.ch/cms-gem-ops/pl/wbntjbexpfgtib5h5nq4e4hbph).

**Review by bdorney — CHANGES_REQUESTED** [review]
Segment into user and developer instructions.  One day the need may arise that a developer would need to take action on the p5 machine.

**Comment by bdorney** [comment]
Is this PR stale?

**Comment by lmoureaux** [comment]
This issue is not stale, he issue you raised is being addressed in #125.

**Comment by bdorney** [comment]
> This issue is not stale, he issue you raised is being addressed in #125.

Given you have #125, and it needs to be made even with central, I would just include these changes there if you have not already done so.

**Comment by lmoureaux** [comment]
> I would just include these changes there if you have not already done so.

It wouldn't fit the topic of #125, "Developer instructions"

**Comment by bdorney** [comment]
> It wouldn't fit the topic of #125, "Developer instructions"

You are able to edit the topic of PR by pressing the `edit` button on the righthand of the screen.

**Comment by lmoureaux** [comment]
This would be against:

> The feature should be compartmentalized as much as possible

(from page 6 of the manifesto)

**Comment by bdorney** [comment]
Update to match central and reopen PR.

**Comment by lmoureaux** [comment]
I already rebased my branch on top of #125, but can't reopen a closed PR.

**Comment by bdorney** [comment]
> I already rebased my branch on top of #125, but can't reopen a closed PR.

:shrug: submit a new one

**Pull request closed without merging**
