### PR TITLE
Addressing issue #22 - Symlinks for mapping/chamberInfo.py

### PR DESCRIPTION
**Pull request by bdorney**
## Description

Addressing: https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/22

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Quality of life improvement.

## How Has This Been Tested?

Tested: http://cmsonline.cern.ch/cms-elog/1005667

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by bdorney** [comment]
After merging with master after recent merge of another PR I have repeated analysis testing:

http://cmsonline.cern.ch/cms-elog/1005667

## Screenshots
fitsummary
summarypruned

**Comment by bdorney** [comment]
@jsturdy the `code-quality/landscape` check has been stuck in `Waiting for status to be reported` for 7 days now...any reason?

**Comment by jsturdy** [comment]
No, I couldn't find why it wasn't running...
For the rest, see my comments on #22, but I can envision forcing this merge later today

**Comment by bdorney** [comment]
For `chamber_vfatMask` it would require a separate PR in `vfatqc-python-tools` to modify `run_scans.py`:

For serial mode (`--series`) it would be straight forward to change line [222](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/master/run_scans.py#L222) too:
```
if link in chamber_vfatMask.keys:
    vfatMask = chamber_vfatMask[link]
else:
    vfatMask = 0x0
```

Then the chamber_vfatMask dict could be empty, and launchArgs would receive the correct input.

However, for the parallel mode I'm not sure how we would edit this for Line [262](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/blob/1b1944142bd102937c3c71db03023fc7057aecaa/run_scans.py#L262).  In addition to for loops can we also include an if statement as described above?

**Comment by jsturdy** [comment]
closing as "On Hold"

**Pull request closed without merging**
