### PR TITLE
Bug Fix: Resolved Errors in ARM DAC Calibration, DAC Analysis and SBIT Rate Plotting

### PR DESCRIPTION
**Pull request by bdorney**
## Description

QC8 team reported problems with ARM DAC calibration analysis; found several `NameError`s and `ValueError`s occurring because string formatting wasn't being performed correctly; also fixed one block of syntax errors.  Finally fixed a bug where only the last scurve to be analyzed was stored in the ARM DAC calibration due to the key in the relevant dictionary already existing.

Noticed in DAC analysis that only the last VFAT that couldn't reach the required bias settings was being stored because the key in the relevant dictionary was already existing.  Fixed.

Fixed an issue in plotting the SBit rate vs. THR DAC plots that caused the y-axis to not report the required range in the `*.png` file saved to disk at the end of the analysis. 

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

Breaking because I flipped the option `--doNotSavePlots` in `ana_scans.py armDacCal` to `--savePlots` as this was causing about 120 png files to be made by default (not necessary...).

## Motivation and Context

Routine unusable.

## How Has This Been Tested?

Tested with QC8 data to make it work.

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jsturdy — APPROVED** [review]

**Comment by jsturdy** [comment]
Hold for #231

**Comment by bdorney** [comment]
> Hold for #231

Rodger doger.

**Comment by jsturdy** [comment]
> > Hold for #231
> 
> Rodger doger.

Actually, given that @bregnery is on holiday, and there are changes, we can sort that out in 2 weeks, release the hold!

**Comment by bdorney** [comment]
> > > Hold for #231
> > 
> > 
> > Rodger doger.
> 
> Actually, given that @bregnery is on holiday, and there are changes, we can sort that out in 2 weeks, release the hold!

Okay if there's no other comments by end of SW dev meeting tomorrow I'll force squash and merge this

**Pull request merged**
