### PR TITLE
Replace nVFATS with nVFats in all instances

### LINKED ISSUE #280: Iterative trimming algorithm for QC8 fails at the first analysis step
## Problem summary
When the trimming algorithm for QC8 is launched, it successfully goes through a single iteration of taking the S-Curves on all chambers, but fails when it reaches the first analysis step.

### Types of issue
- [X] Bug report (report an issue with the code)
- [ ] Feature request (request for change which adds functionality)

## Expected Behavior
The algorithm should take a single S-Curve of each detector specified by the chamber mask in the calling command. It should then analyze those S-Curves, and repeat the process up to the specified number (3) of times.

## Current Behavior
When the trimming algorithm for QC8 is launched, it successfully goes through a single iteration of taking the S-Curves on all chambers, but fails when it reaches the first analysis step. In the terminal, it reports:

```
Finished iterativeTrimming all optohybrids on shelfX slotY in ohMask: 0xABC
```

However, when you look at the scanLog for any given detector, you see the following after it finishes scanning all 128 channels:

```
 scurve finished
 Analyzing scurve /data/bigdisk/GEM-Data-Taking/GE11_QC8//GE11-X-S-INDIA-0016/itertrim//2020.01.29.14.08/SCurveData_iter1.root
 Traceback (most recent call last):
   File "/opt/cmsgemos/bin/iterativeTrim.py", line 275, in 
     scurveFitResults = iterativeTrim(args,dirPath,identifier,chanRegData=dict_chanRegArray[iterNum-1], calInfo=tuple_calInfo)
   File "/opt/cmsgemos/bin/iterativeTrim.py", line 107, in iterativeTrim
     return fitScanData(treeFileName=filename, isVFAT3=True, calTuple=calInfo)
   File "/usr/lib/python2.7/site-packages/gempython/gemplotting/fitting/fitScanData.py", line 450, in fitScanData
     nVFATS=nVFATS
 TypeError: __init__() got an unexpected keyword argument 'nVFATS'
```
### Steps to Reproduce (for bugs)
1. From the `gem904qc8daq` machine, configure the chambers for trimming: `confAllChambers.py --shelf=1 --vfatConfig --chConfig --applyMasks --run`
2. Launch the following command for each column in QC8: `run_scans.py itertrim X Y 0xABC --maxIter 3 --sigmaOffset -4 --highTrimCutoff 50 --highTrimWeight 50 --highNoiseCut 1.5`
3. Reference `scanLog.log` for each of the chambers.

## Possible Solution (for bugs)
`nVFATS` should be `nVFats` in several places in the code.

## Your Environment
* Version used:
* Shell used: Mac OS terminal

### PR DESCRIPTION
**Pull request by ElizabethRoseStarling**
## Description

Replaced nVFATS with nVFats in all instances so iterativeTrim.py can function correctly.

### Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

Fixes [Issue 280](https://github.com/cms-gem-daq-project/gem-plotting-tools/issues/280).

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by jsturdy** [comment]
without knowing anything else about the context of this change, coding style consistency would say this change should be `nVFATS` -> `nVFATs`
(and if this change was made to make something match an `nVfats` elsewhere, that other location should be changed from `nVfats` -> `nVFATs`)

**Comment by lpetre-ulb** [comment]
The most used variable name is `nVFATS`:
``` bash
[lpetre@gem-daq gem-plotting-tools]$ grep -hori nvfats pkg | sort | uniq -c
     15 nVFats
      1 nVFATs        # which is a comment
     99 nVFATS
```
with `nVFats` used mainly in `fitting/fitScanData.py`, three times in `chamberInfo.py` and once in `utils/scurveAlgos.py` (for compatibility with the first file).

I guess the simplest change would be to convert the `nVFats` to `nVFATS`(which was introduced in the [GE2/1 generalizing PR](https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/252/files)).

The best change for code style consistency would be your suggestion. However, it requires the largest number of changes (with the associated issues) and would probably require changes in the [GE2/1 PR from `vfatqc-python-scripts`](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/265).

**Comment by jsturdy** [comment]
> The most used variable name is `nVFATS`:
> 
> ```shell
> [lpetre@gem-daq gem-plotting-tools]$ grep -hori nvfats pkg | sort | uniq -c
>      15 nVFats
>       1 nVFATs        # which is a comment
>      99 nVFATS
> ```
> 
> with `nVFats` used mainly in `fitting/fitScanData.py`, three times in `chamberInfo.py` and once in `utils/scurveAlgos.py` (for compatibility with the first file).
> 
> I guess the simplest change would be to convert the `nVFats` to `nVFATS`(which was introduced in the [GE2/1 generalizing PR](https://github.com/cms-gem-daq-project/gem-plotting-tools/pull/252/files)).
> 

:+1: for least invasive correction as a hotfix, with a potential cleanup later

> The best change for code style consistency would be your suggestion. However, it requires the largest number of changes (with the associated issues) and would probably require changes in the [GE2/1 PR from `vfatqc-python-scripts`](https://github.com/cms-gem-daq-project/vfatqc-python-scripts/pull/265).

**Comment by mexanick** [comment]
superseeded by #284

**Pull request closed without merging**
