### PR TITLE
Ignore files generated by "make rpm"

### PR DESCRIPTION
**Pull request by lmoureaux**
## Description

Add the following entries to .gitignore:

```
pkg/LICENSE
pkg/MANIFEST.in
pkg/README.md
pkg/gempython
pkg/requirements.txt
rpm
```

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Motivation and Context

After running `make rpm` or `make pip`, `git` thinks that the tree is dirty.

## How Has This Been Tested?

Ran `git status` after `make pip` and `make rpm` to ensure that I didn't miss any file.

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by bdorney** [comment]
In the interim as a reminder never use `git add -a .`

**Comment by lmoureaux** [comment]
> Actually it would be even better if you force `.gitignore` to ignore everything with certain exceptions (like do not ignore *.py or *.h etc).

That's what the existing `.gitignore` does, but `make` creates Python and Markdown files in a "source" directory (`pkg`), and an additional directory (`rpm`). In your example, I can see the following:
```
# Ignore RPM directories
*/rpm
```
This is close to what I do in this PR.

**Comment by mexanick** [comment]
actually, l37 in the example is not quite required... What I would rather like to see:
```
# Ignore everything
*
# Don't ignore subdirectories
!*/
# Don't ignore source files, etc
!*.gitignore
!*.c
!*.cpp
!*.cc
!*.C
!*.h
!*.hh
!*.hpp
!*.py
```

**Comment by mexanick** [comment]
in this case even `git commit -a` won't really add too much )

**Comment by lmoureaux** [comment]
@mexanick Please take a look at the [existing `.gitignore`](https://github.com/cms-gem-daq-project/gem-plotting-tools/blob/develop/.gitignore).

**Comment by mexanick** [comment]
ehm, how come then that pkg/<smth> and rpm/<smth> become trackable by git? Did someone add them? If so, `git rm` will help =)

**Comment by lmoureaux** [comment]
> how come then that pkg/ and rpm/ become trackable by git?
```
# Don't ignore subdirectories
!*/
```

In addition, `pkg` contains tracked files that are needed to build the package.

**Comment by jsturdy** [comment]
Sorry I didn't see this in time to prevent this merge, but you implemented it in a non-optimal way...
As @lmoureaux noted, you can *easily* ignore a specific directory even after `!*/` in the `.gitignore`, so I'm not sure why `pkg` as a whole wasn't ignored, and the few tracked files unignored...
Also, I'm not sure why this was an issue in the first place...
I would probably be in favour of reverting this and if deciding to go forward, doing it "right"

**Comment by bdorney** [comment]
As you wish.

> ...this in time to prevent this merge...

To prevent further issues in the future perhaps we could set a designated time per week that approved PR's get merged.

I think the weekly Friday ops meeting might be an ideal time period.

**Pull request merged**
